import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SearchHeader from "@/components/SearchHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//git remote add origin git@github.com:truongnhatcuong/projectGoogle.git
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={inter.className}>
      <SearchHeader />
      {children}
    </div>
  );
}
